# traefik/traefik.yml  (STATİK)
# Static configuration
api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: lezzetlimani32@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO # DEBUG only when needed